let itemsArray = [
    {
        id: 1,
        type: "begging set",
        size: "king, queen",
        color: "white",
        queensPrice: 249,
        kingsPrice: 299,
        img1: "white-1.jpg",
        img2: "white-1.jpg",
        img3: "white-1.jpg",
    },
    {
        id: 2,
        type: "begging set",
        size: "king, queen",
        color: "silver grey",
        queensPrice: 249,
        kingsPrice: 299,
        img1: "silver-gray-1.jpg",
        img2: "silver-gray-1.jpg",
        img3: "silver-gray-1.jpg",
    },
    {
        id: 3,
        type: "begging set",
        size: "king, queen",
        color: "light green",
        queensPrice: 249,
        kingsPrice: 299,
        img1: "light-green-1.jpg",
        img2: "light-green-1.jpg",
        img3: "light-green-1.jpg",
    },
    {
        id: 4,
        type: "begging set",
        size: "king, queen",
        color: "light pink",
        queensPrice: 249,
        kingsPrice: 299,
        img1: "light-pink-1.jpg",
        img2: "light-pink-1.jpg",
        img3: "light-pink-1.jpg",
    },
    {
        id: 5,
        type: "begging set",
        size: "king, queen",
        color: "shell",
        queensPrice: 249,
        kingsPrice: 299,
        img1: "shell-1.jpg",
        img2: "shell-1.jpg",
        img3: "shell-1.jpg",
    },
    {
        id: 6,
        type: "begging set",
        size: "king, queen",
        color: "skin color",
        queensPrice: 249,
        kingsPrice: 299,
        img1: "skin-color-1.jpg",
        img2: "skin-color-1.jpg",
        img3: "skin-color-1.jpg",
    },
    {
        id: 7,
        type: "begging set",
        size: "king, queen",
        color: "young pink",
        queensPrice: 249,
        kingsPrice: 299,
        img1: "young-pink-1.jpg",
        img2: "young-pink-1.jpg",
        img3: "young-pink-1.jpg",
    },
    {
        id: 8,
        type: "begging set",
        size: "king, queen",
        color: "forest",
        queensPrice: 249,
        kingsPrice: 299,
        img1: "forest-1.jpg",
        img2: "forest-1.jpg",
        img3: "forest-1.jpg",
    },
    {
        id: 9,
        type: "begging set",
        size: "king, queen",
        color: "rose pink",
        queensPrice: 249,
        kingsPrice: 299,
        img1: "rose-pink-1.jpg",
        img2: "rose-pink-1.jpg",
        img3: "rose-pink-1.jpg",
    },
    {
        id: 10,
        type: "begging set",
        size: "king, queen",
        color: "young blue",
        queensPrice: 249,
        kingsPrice: 299,
        img1: "young-blue-1.jpg",
        img2: "young-blue-1.jpg",
        img3: "young-blue-1.jpg",
    },
    {
        id: 11,
        type: "begging set",
        size: "king, queen",
        color: "sage",
        queensPrice: 249,
        kingsPrice: 299,
        img1: "sage-1.jpg",
        img2: "sage-1.jpg",
        img3: "sage-1.jpg",
    },
    {
        id: 12,
        type: "begging set",
        size: "king, queen",
        color: "orange",
        queensPrice: 249,
        kingsPrice: 299,
        img1: "orange-1.jpg",
        img2: "orange-1.jpg",
        img3: "orange-1.jpg",
    },
    {
        id: 13,
        type: "begging set",
        size: "king, queen",
        color: "earth brown",
        queensPrice: 249,
        kingsPrice: 299,
        img1: "earh-brown-1.jpg",
        img2: "earh-brown-1.jpg",
        img3: "earh-brown-1.jpg",
    },
    {
        id: 14,
        type: "begging set",
        size: "king, queen",
        color: "charming blue",
        queensPrice: 249,
        kingsPrice: 299,
        img1: "charming-blue-1.jpg",
        img2: "charming-blue-1.jpg",
        img3: "charming-blue-1.jpg",
    },
    {
        id: 15,
        type: "begging set",
        size: "king, queen",
        color: "steel gray",
        queensPrice: 249,
        kingsPrice: 299,
        img1: "steel-gray-1.jpg",
        img2: "steel-gray-1.jpg",
        img3: "steel-gray-1.jpg",
    },
    {
        id: 16,
        type: "begging set",
        size: "king, queen",
        color: "dark grey",
        queensPrice: 249,
        kingsPrice: 299,
        img1: "dark-grey-1.jpg",
        img2: "dark-grey-1.jpg",
        img3: "dark-grey-1.jpg",
    },
    {
        id: 17,
        type: "begging set",
        size: "king, queen",
        color: "charcoal gray",
        queensPrice: 249,
        kingsPrice: 299,
        img1: "charcoal-grey-1.jpg",
        img2: "charcoal-grey-1.jpg",
        img3: "charcoal-grey-1.jpg",
    },
];

export default itemsArray;
